services:
  loki:
    image: grafana/loki:3.6.0
    container_name: loki_prod
    user: "0:0"
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki.yaml
      - loki-data-prod:/loki
      - loki-wal-prod:/wal
    command: -config.file=/etc/loki/loki.yaml
    restart: always

  promtail:
    image: grafana/promtail:3.6.0
    container_name: promtail_prod
    user: "0:0"
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_prod
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data-prod:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=90d"
    restart: always

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter_prod
    ports:
      - "9100:9100"
    restart: always

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana_prod
    ports:
      - "3000:3000"
    volumes:
      - grafana-data-prod:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
      - loki
    restart: always

  app:
    container_name: school_app_preprod
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./school_app:/app
    env_file:
      - .env
    depends_on:
      - loki
    restart: always

volumes:
  grafana-data-prod:
  prometheus-data-prod:
  loki-data-prod:
  loki-wal-prod: